### ISSUE TITLE
How to configure for jest?

### ISSUE THREAD

**Issue by manumaticx** [jeeyah/jestscreenshot#3]
Got this:
```
Failed: jasmine is not defined
      ReferenceError: jasmine is not defined
      at exports.init (node_modules/@jeeyah/jestscreenshot/index.js:22:3)
```

**Comment by wadeziegler** [comment]
If you are running the test with jest then jasmine is defined globally. This was originally tested with jest 23.6.0. I just tested it again with version the newest version 24.8.0.

Take a look at the tests directory for an example of how to use it.

**Comment by k1832** [comment]
I had the same problem with @manumaticx . But I managed to find why it was not working.
I used to use jest-circus as a test runner, which is not default (default is jasmine2).
https://jestjs.io/docs/ja/configuration#testrunner-string

After I set the test runner to default, it's working correctly.
