### ISSUE TITLE
Project seems abandoned with broken code

### ISSUE THREAD

**Issue by Favna** [jeeyah/jestscreenshot#4]
The single PR that fixes the totally broken code and the fact that `Promise.waitAll` is not even an existing function means this code is pretty much broken. No fixes seem to be coming any time soon and assuming Jeeyah has completely abandoned the project but this repo does pop up on Google searches I figured it be a good idea to share some stuff here.

As we required it at work we have implemented an as-package-useable variant of this solution + some code snippets from an issue on the jest-puppeteer repo.

For those interested we published the package publically here: [npm](https://www.npmjs.com/package/@rws-air/jestscreenshot)

**Comment by redrockzee** [comment]
There have been very few issues. So, there has been no need to make changes. The del dependency PR you refer to has been fixed.
